package(default_visibility = [
    "//visibility:public"
])

load("//config:variables.bzl", "COPTS")

cc_library(
    name = "thread_pool",
    hdrs = ["thread_pool.h"],
    srcs = ["thread_pool.cc"],
    deps = [],
    copts = COPTS,
)

